service: aws-python # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  environment:
    host: 'localhost'
    user: 'edu'
    password: 'flashcards'
    database: 'flashcards'

# 'functions' in serverless.yml
functions:
  # to teste application
  ping:
    handler: src/API/ping.pingDatabase

  # To manager subject
  create_subject:
    handler: src/API/subject/createSubject.create
  get_subject:
    handler: src/API/subject/readSubject.read
  delete_subject:
    handler: src/API/subject/deleteSubject.delete
  update_subject:
    handler: src/API/subject/updateSubject.update

  # To manager category
  create_category:
    handler: src/API/category/createCategory.create
  get_category:
    handler: src/API/category/readCategory.read
  delete_category:
    handler: src/API/category/deleteCategory.delete
  update_category:
    handler: src/API/category/updateCategory.update

  # To manager response
  create_response:
    handler: src/API/response/createResponse.create
  get_response:
    handler: src/API/response/readResponse.read
  delete_response:
    handler: src/API/response/deleteResponse.delete
  update_response:
    handler: src/API/response/updateResponse.update

  # To manager question
  create_question:
    handler: src/API/question/createQuestion.create
  get_question:
    handler: src/API/question/readQuestion.read
  delete_question:
    handler: src/API/question/deleteQuestion.delete
  update_question:
    handler: src/API/question/updateQuestion.update
