service: aws-python # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  environment:
    host: 'localhost'
    user: 'edu'
    password: 'flashcards'
    database: 'flashcards'

# 'functions' in serverless.yml
functions:
  ping:
    handler: src/API/ping.pingDatabase # Reference to file handler.js & exported function 'users'
  card: # Function name
    handler: src/API/cards/createCards.create # Reference to file handler.js & exported function 'users'
    events: # All events associated with this function
      - httpApi: 'POST /users/create'
#        - httpApi: 'PUT /users/update'
#        - httpApi: 'DELETE /users/delete'