service: aws-python # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  environment:
    host: 'localhost'
    user: 'edu'
    password: 'flashcards'
    database: 'flashcards'

# 'functions' in serverless.yml
functions:
  ping:
    handler: src/API/ping.pingDatabase # Reference to file handler.js & exported function 'users'
  card:
    handler: src/API/cards.sql/createCards.create # Reference to file handler.js & exported function 'users'
  get_category:
    handler: src/API/category/readCategory.read
  delete_category:
    handler: src/API/category/deleteCategory.delete
  update_category:
    handler: src/API/category/updateCategory.update
