org: eduardolima
app: aws-python
service: aws-python # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

  environment:
    host: 'localhost'
    user: 'edu'
    password: 'flashcards'
    database: 'flashcards'

# 'functions' in serverless.yml
functions:
  # to teste application
  ping:
    handler: src/API/ping.pingDatabase
    events:
      - httpApi: 'GET /ping'

  # To manager cards
  create_cards:
    handler: src/API/cards/createCards.create
    events:
      - httpApi: 'POST /create_cards'
  get_cards:
    handler: src/API/cards/readCards.read
    events:
      - httpApi: 'GET /get_cards'
  get_cards_by_topic:
    handler: src/API/cards/getCardsByTopic.get_cards_by_topic
    events:
      - httpApi: 'GET /get_cards_by_topic'
  delete_cards:
    handler: src/API/cards/deleteCards.delete
    events:
      - httpApi: 'DELETE /delete_cards'
  update_cards:
    handler: src/API/cards/updateCards.update
    events:
      - httpApi: 'PUT /update_cards'

  # To manager topic
  create_topic:
    handler: src/API/topic/createTopic.create
    events:
      - httpApi: 'POST /create_topic'
  get_topic:
    handler: src/API/topic/readTopic.read
    events:
      - httpApi: 'GET /get_topic'
  get_topic_by_category:
    handler: src/API/topic/getTopicByCategory.get_topic_by_category
    events:
      - httpApi: 'GET /get_topic_by_category'
  delete_topic:
    handler: src/API/topic/deleteTopic.delete
    events:
      - httpApi: 'DELETE /delete_topic'
  update_topic:
    handler: src/API/topic/updateTopic.update
    events:
      - httpApi: 'PUT /update_topic'

  # To manager category
  create_category:
    handler: src/API/category/createCategory.create
    events:
      - httpApi: 'POST /create_category'
  get_category:
    handler: src/API/category/readCategory.read
    events:
      - httpApi: 'GET /get_category'
  get_category_by_user:
    handler: src/API/category/getCategoryByUser.get_category_by_user
    events:
      - httpApi: 'GET /get_category_by_user'
  delete_category:
    handler: src/API/category/deleteCategory.delete
    events:
      - httpApi: 'DELETE /delete_category'
  update_category:
    handler: src/API/category/updateCategory.update
    events:
      - httpApi: 'PUT /update_category'

  # To manager login
  create_login:
    handler: src/API/login/createLogin.create
    events:
      - httpApi: 'POST /create_login'
  get_login:
    handler: src/API/login/readLogin.read
    events:
      - httpApi: 'GET /get_login'
  delete_login:
    handler: src/API/login/deleteLogin.delete
    events:
      - httpApi: 'DELETE /delete_login'
  update_login:
    handler: src/API/login/updateLogin.update
    events:
      - httpApi: 'PUT /update_login'

