-- MySQL Script generated by MySQL Workbench
-- ter 25 jul 2023 20:32:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flashcards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flashcards` DEFAULT CHARACTER SET utf8 ;
USE `flashcards` ;

-- -----------------------------------------------------
-- Table `flashcards`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashcards`.`usuarios` (
  `id_usuário` INT NOT NULL,
  PRIMARY KEY (`id_usuário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashcards`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashcards`.`categorias` (
  `id_categoria` INT NOT NULL,
  `id_usuario` INT NULL,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `ativo` INT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_categorias_1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `flashcards`.`usuarios` (`id_usuário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashcards`.`assuntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashcards`.`assuntos` (
  `id_assunto` INT NOT NULL,
  `id_categoria` INT NULL,
  `tipo` ENUM('NORMAL', 'INTELIGENTE') NOT NULL,
  `nome_assunto` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `ativo` INT NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_assunto`),
  INDEX `fk_assuntos_1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_assuntos_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `flashcards`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashcards`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashcards`.`pergunta` (
  `id_pergunta` INT NOT NULL,
  `pergunta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pergunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashcards`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashcards`.`resposta` (
  `id_resposta` INT NOT NULL,
  `resposta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_resposta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flashcards`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flashcards`.`cards` (
  `id_cards` INT NOT NULL,
  `id_pergunta` INT NULL,
  `id_resposta` INT NULL,
  `id_assunto` INT NULL,
  `ativo` INT NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id_cards`),
  INDEX `fk_cards_1_idx` (`id_assunto` ASC) VISIBLE,
  INDEX `fk_cards_2_idx` (`id_pergunta` ASC) VISIBLE,
  INDEX `fk_cards_3_idx` (`id_resposta` ASC) VISIBLE,
  CONSTRAINT `fk_cards_1`
    FOREIGN KEY (`id_assunto`)
    REFERENCES `flashcards`.`assuntos` (`id_assunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_2`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `flashcards`.`pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_3`
    FOREIGN KEY (`id_resposta`)
    REFERENCES `flashcards`.`resposta` (`id_resposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
